# Generated by Django 4.1.6 on 2023-02-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_car', '0002_alter_car_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='renters',
            field=models.ManyToManyField(through='my_app_car.Rent', to='my_app_car.person'),
        ),
    ]
