# Generated by Django 4.1.6 on 2023-02-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_car', '0003_car_renters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='renters',
            field=models.ManyToManyField(blank=True, null=True, through='my_app_car.Rent', to='my_app_car.person'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
