# Generated by Django 4.1.6 on 2023-02-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_car', '0005_alter_rent_end_date_alter_rent_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='renters',
            field=models.ManyToManyField(blank=True, null=True, related_name='rented_cars', through='my_app_car.Rent', to='my_app_car.person'),
        ),
    ]
